### ISSUE TITLE
Bug Report: No headset window on taskbar (Freetrack)

### ISSUE THREAD

**Issue by TheRealMesteven** [r57zone/OpenVR-OpenTrack#31] opened 2023-10-26 05:02 UTC
First time running it, it ran as expected and was fully functional. Second day, I boot it up and I get the headset window but it doesnt appear on the taskbar and as soon as I click or interact with anything the window disappears into the void.

**Comment by TheRealMesteven** [comment] 2023-10-26 05:15
With the bug, trying to get it to display on another monitor briefly displays it on the other monitor before immediately closing the window.

**Comment by r57zone** [comment] 2023-10-26 09:10
I checked, it looks like Valve updated SteamVR and the drivers stopped working again, too bad. There are no ideas yet on how to fix this.

**Comment by r57zone** [comment] 2023-10-26 10:46
https://github.com/ValveSoftware/openvr/issues/1780

**Comment by r57zone** [comment] 2023-11-21 20:06
As a temporary solution, you can use an old version of SteamVR.
1. Uninstall the current SteamVR.
2. [Unzip this file](https://github.com/r57zone/VR-tracking-apps/releases/download/1/SteamVR.1.18.31.07.21.7z) to C:\Program Files\SteamVR.
3. Run "vrstartup.exe".

**Comment by ivan046** [comment] 2023-12-06 17:32
Another temporary solution: https://github.com/ValveSoftware/openvr/issues/1780#issuecomment-1821645037

> restarting the VRCompositor seems to help and the window won't vanish afterwards!
> 
> `PS C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64> get-process vrcompositor | stop-process -Force;.\vrcompositor.exe`

**Comment by r57zone** [comment] 2023-12-14 18:36
The problem is fixed in beta 2.2.1  - https://store.steampowered.com/news/app/250820/view/3873722126474526180

**Closed as completed by r57zone** 2023-12-14 18:36 UTC
